import Config

# Configure your database
# Use DATABASE_URL if set (for Docker), otherwise use individual settings
if db_url = System.get_env("DATABASE_URL") do
  config :alethea, Alethea.Repo, url: db_url, pool_size: 10
else
  config :alethea, Alethea.Repo,
    username: "postgres",
    password: "postgres",
    hostname: "localhost",
    database: "alethea_dev",
    pool_size: 10
end

config :alethea, Alethea.Repo,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :alethea, AletheaWeb.Endpoint,
  # Binding to all interfaces for Docker
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "w+TyKvbADEtPOxD29w8fGJLnR/F1YiMpe2YmHZvmfqfPOg9PqzF8bziBYch8/U8r",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :alethea, AletheaWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/alethea_web/router\.ex$",
      ~r"lib/alethea_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :alethea, dev_routes: true

config :alethea,
       :phone_hash_secret,
       "dev_test_phone_hash_secret_key_32_bytes_minimum_length_fallback"

config :alethea, :whatsapp,
  api_token: System.get_env("WHATSAPP_API_TOKEN", "mock"),
  phone_number_id: System.get_env("WHATSAPP_PHONE_NUMBER_ID", "mock"),
  app_secret: System.get_env("WHATSAPP_APP_SECRET"),
  verify_token: System.get_env("WHATSAPP_VERIFY_TOKEN", "alethea2026")

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :alethea, use_mock_data: false

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :alethea, Alethea.AI.RoBERTaWorker,
  provider: :huggingface,
  huggingface: [
    api_url:
      "https://api-inference.huggingface.co/models/pysentimiento/robertuito-emotion-analysis",
    api_key: System.get_env("ROBERTA_HF_API_KEY", "")
  ]

config :alethea, Alethea.AI.Chains.GuidedConversationChain,
  provider: :local,
  local: [
    endpoint_url: "http://localhost:11434/v1",
    api_key: "ollama"
  ]

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Dev-only fallback for the Vault encryption key.
# This key is NOT secret — it exists solely to allow `mix phx.server` without env vars.
# NEVER use this value in production.
config :alethea, Alethea.Encryption.Vault,
  aes_key: System.get_env("CLOAK_AES_KEY", "lcCL8CL/9+jxk2PmCJwpmkKc1PrJ8nlO9NDhsh/6UKc=")

# Telegram Client adapter override for :dev (PR #3a / TASK-3a-4).
# The config/config.exs default is the Req production adapter; :dev
# overrides to the Fake so `mix phx.server` does NOT hit the real
# Telegram API by accident. The Fake accumulates sends in ETS and is
# inspected via `iex> Alethea.Telegram.Client.Fake.sends/0`.
config :alethea, :telegram_client, Alethea.Telegram.Client.Fake
