#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

fail() {
  printf '  %sError:%s %s\n' "$RED" "$RESET" "$1" >&2
  exit 1
}

generate_base64_secret() {
  openssl rand -base64 32 | tr -d '\n'
}

generate_webhook_secret() {
  openssl rand -hex 32
}

secret_byte_count() {
  LC_ALL=C printf '%s' "$1" | wc -c | tr -d ' '
}

ensure_generated_secret() {
  local key="$1" current generated
  current=$(_existing "$key" || true)

  if [[ -n "$current" ]]; then
    if confirm "Replace existing $key? Rotation may make existing encrypted or linked data unusable."; then
      generated=$(generate_base64_secret)
      write_env "$key" "$generated"
      printf -v "$key" '%s' "$generated"
    else
      printf -v "$key" '%s' "$current"
      say "Preserved existing $key without displaying it."
    fi
  else
    generated=$(generate_base64_secret)
    write_env "$key" "$generated"
    printf -v "$key" '%s' "$generated"
  fi
}

ensure_pepper() {
  local current generated bytes
  current=$(_existing TELEGRAM_CHAT_ID_PEPPER || true)

  if [[ -n "$current" ]]; then
    bytes=$(secret_byte_count "$current")
    if (( bytes < 32 )); then
      warn "Existing TELEGRAM_CHAT_ID_PEPPER is shorter than 32 bytes and cannot be used."
      confirm "Replace it with a generated 32-byte value?" || fail "A valid pepper is required."
      generated=$(generate_base64_secret)
      write_env TELEGRAM_CHAT_ID_PEPPER "$generated"
      TELEGRAM_CHAT_ID_PEPPER="$generated"
    elif confirm "Replace existing TELEGRAM_CHAT_ID_PEPPER? Existing Telegram chat links will stop matching."; then
      generated=$(generate_base64_secret)
      write_env TELEGRAM_CHAT_ID_PEPPER "$generated"
      TELEGRAM_CHAT_ID_PEPPER="$generated"
    else
      TELEGRAM_CHAT_ID_PEPPER="$current"
      say "Preserved existing TELEGRAM_CHAT_ID_PEPPER without displaying it."
    fi
  else
    generated=$(generate_base64_secret)
    write_env TELEGRAM_CHAT_ID_PEPPER "$generated"
    TELEGRAM_CHAT_ID_PEPPER="$generated"
  fi
}

ensure_captured_secret() {
  local key="$1" prompt="$2" current value
  current=$(_existing "$key" || true)

  if [[ -n "$current" ]]; then
    if confirm "Replace existing $key?"; then
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
      read -rs value || true
      printf '\n'
      [[ -n "$value" ]] || fail "$key cannot be empty."
      write_env "$key" "$value"
      printf -v "$key" '%s' "$value"
    else
      printf -v "$key" '%s' "$current"
      say "Preserved existing $key without displaying it."
    fi
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    read -rs value || true
    printf '\n'
    [[ -n "$value" ]] || fail "$key cannot be empty."
    write_env "$key" "$value"
    printf -v "$key" '%s' "$value"
  fi
}

ensure_exact_env() {
  local key="$1" required="$2" current
  current=$(_existing "$key" || true)

  if [[ -z "$current" ]]; then
    write_env "$key" "$required"
  elif [[ "$current" == "$required" ]]; then
    say "Preserved existing $key."
  elif confirm "Replace existing $key with the required demo value '$required'?"; then
    write_env "$key" "$required"
  else
    fail "$key must be '$required' for this approved demo. Existing value was preserved."
  fi
}

umask 077

banner "Alethea Telegram synthetic demo setup"

# ── Stage 1: prerequisites ─────────────────────────────────────────────────
stage "Verify local prerequisites"
say "This wizard verifies dependencies but never installs software for you."
prerequisite_failed=0

if ! command -v pg_isready >/dev/null 2>&1; then
  warn "PostgreSQL client tools are missing (pg_isready was not found)."
  note "macOS/Homebrew: brew install postgresql@16"
  note "Debian/Ubuntu: sudo apt install postgresql postgresql-client"
  prerequisite_failed=1
elif ! pg_isready -h localhost >/dev/null 2>&1; then
  warn "PostgreSQL is installed but is not accepting connections on localhost."
  note "macOS/Homebrew: brew services start postgresql@16"
  note "Linux: start your distribution's postgresql service, then rerun this wizard."
  prerequisite_failed=1
else
  say "PostgreSQL is accepting connections on localhost."
fi

if ! command -v curl >/dev/null 2>&1; then
  warn "curl is required for local health checks and Telegram webhook registration."
  prerequisite_failed=1
fi

if ! command -v openssl >/dev/null 2>&1; then
  warn "openssl is required to generate local secrets safely."
  prerequisite_failed=1
fi

if ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
  warn "Docker with Compose is required for the persistent emotion sidecar."
  prerequisite_failed=1
fi

if ! command -v ollama >/dev/null 2>&1; then
  warn "Ollama is missing. Install it from https://ollama.com/download, then rerun."
  prerequisite_failed=1
elif ! curl -fsS http://localhost:11434/api/tags >/dev/null 2>&1; then
  warn "Ollama is installed but its local service is not reachable."
  note "Start 'ollama serve' in another terminal (or launch the Ollama app), then rerun."
  prerequisite_failed=1
elif ! ollama list 2>/dev/null | awk 'NR > 1 {print $1}' | grep -Eq '^phi4-mini(:|$)'; then
  warn "The phi4-mini model is not available locally."
  note "Run 'ollama pull phi4-mini' yourself, then rerun this wizard."
  prerequisite_failed=1
else
  say "Ollama is reachable and phi4-mini is available."
fi

if ! command -v cloudflared >/dev/null 2>&1; then
  warn "cloudflared is missing. Follow the official install guide:"
  note "https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
  prerequisite_failed=1
else
  say "cloudflared is installed."
fi

if (( prerequisite_failed )); then
  fail "Resolve the prerequisite warnings above and rerun the wizard. Nothing was installed."
fi

# ── Stage 2: persistent local runtime configuration ────────────────────────
stage "Configure local secrets and Ollama"
say "Only local runtime values belong in .env. Values are never displayed."
warn "Do not rotate CLOAK_AES_KEY after data has been encrypted. Keep a secure backup."
ensure_generated_secret CLOAK_AES_KEY
ensure_pepper
ensure_exact_env AI_PROVIDER local
ensure_exact_env LLM_MODEL phi4-mini
ensure_exact_env LOCAL_LLM_BASE_URL http://localhost:11434
ensure_exact_env EMOTION_SIDECAR_URL http://127.0.0.1:8080
ensure_exact_env TELEGRAM_CLIENT_ADAPTER req
say "Local runtime configuration is ready. Telegram bot credentials are intentionally excluded."

# ── Stage 3: encrypted Telegram bot configuration ──────────────────────────
stage "Configure the Telegram bot"
say "BotFather supplies the bot token and username. The webhook secret is generated locally."
open_url "https://t.me/BotFather"
step "In the verified BotFather chat, use /newbot for a new bot or /mybots for an existing bot."
step "Follow BotFather's prompts and copy the HTTP API token."
printf '  %sPaste the Telegram bot token (hidden):%s ' "$BOLD" "$RESET"
read -rs TELEGRAM_BOT_TOKEN || true
printf '\n'
[[ "$TELEGRAM_BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]] || fail "The Telegram bot token format is invalid."

step "Copy the bot username shown by BotFather (with or without the leading @)."
printf '  %sPaste the Telegram bot username:%s ' "$BOLD" "$RESET"
read -r TELEGRAM_BOT_USERNAME || true
TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME#@}
[[ "$TELEGRAM_BOT_USERNAME" =~ ^[A-Za-z0-9_]{5,32}$ ]] || fail "The bot username must contain 5 to 32 letters, digits, or underscores."

printf '  %sPaste a webhook secret, or press Enter to generate one (hidden):%s ' "$BOLD" "$RESET"
read -rs TELEGRAM_WEBHOOK_SECRET || true
printf '\n'
if [[ "$TELEGRAM_WEBHOOK_SECRET" =~ ^[[:space:]]*$ ]]; then
  TELEGRAM_WEBHOOK_SECRET=$(generate_webhook_secret)
fi
[[ "$TELEGRAM_WEBHOOK_SECRET" =~ ^[A-Za-z0-9_-]+$ && ${#TELEGRAM_WEBHOOK_SECRET} -le 256 ]] || fail "The webhook secret contains unsupported characters."

warn "This writes or replaces the encrypted Telegram BotConfig row for env=dev."
confirm "Continue with the encrypted database update?" || fail "Telegram BotConfig was not changed."

if ! TELEGRAM_BOOTSTRAP_OUTPUT=$(
  TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN" \
  TELEGRAM_WEBHOOK_SECRET="$TELEGRAM_WEBHOOK_SECRET" \
  TELEGRAM_BOT_USERNAME="$TELEGRAM_BOT_USERNAME" \
  mix alethea.telegram.bootstrap --env dev
); then
  fail "Telegram bootstrap failed. Review the Mix error above; no credential was written to .env."
fi
[[ "$TELEGRAM_BOOTSTRAP_OUTPUT" == *"TELEGRAM_BOT_CONFIGURED_ENV=dev"* ]] || fail "Telegram bootstrap did not return its expected confirmation."
unset TELEGRAM_BOOTSTRAP_OUTPUT
say "Telegram credentials are encrypted in the database and remain temporary in this wizard process."

# ── Stage 4: synthetic demo identity and deep link ─────────────────────────
stage "Bootstrap the synthetic demo identity"
warn "This demo accepts synthetic data only. Never use a real patient identity or journal entry."
printf '  %sEnter a synthetic-only demo password, 12 to 72 characters (hidden):%s ' "$BOLD" "$RESET"
read -rs ALETHEA_DEMO_PROFESSIONAL_PASSWORD || true
printf '\n'
if (( ${#ALETHEA_DEMO_PROFESSIONAL_PASSWORD} < 12 || ${#ALETHEA_DEMO_PROFESSIONAL_PASSWORD} > 72 )); then
  fail "The synthetic demo password must be 12 to 72 characters."
fi

if ! DEMO_BOOTSTRAP_OUTPUT=$(
  ALETHEA_DEMO_PROFESSIONAL_PASSWORD="$ALETHEA_DEMO_PROFESSIONAL_PASSWORD" \
  mix alethea.demo.bootstrap --synthetic --env dev
); then
  unset ALETHEA_DEMO_PROFESSIONAL_PASSWORD
  fail "Synthetic demo bootstrap failed. Review the Mix error above."
fi
unset ALETHEA_DEMO_PROFESSIONAL_PASSWORD

ALETHEA_TELEGRAM_ONBOARDING_URL=""
while IFS= read -r output_line; do
  case "$output_line" in
    ALETHEA_TELEGRAM_ONBOARDING_URL=*)
      ALETHEA_TELEGRAM_ONBOARDING_URL=${output_line#ALETHEA_TELEGRAM_ONBOARDING_URL=}
      ;;
  esac
done <<< "$DEMO_BOOTSTRAP_OUTPUT"
unset DEMO_BOOTSTRAP_OUTPUT output_line
[[ "$ALETHEA_TELEGRAM_ONBOARDING_URL" == https://t.me/* ]] || fail "The demo task did not return a valid onboarding URL."
say "Captured the short-lived onboarding URL without printing or persisting it."
warn "The onboarding credential expires after 10 minutes. Continue without delay."

# ── Stage 5: long-lived local processes ────────────────────────────────────
stage "Start the sidecar, Phoenix, and a Cloudflare quick tunnel"
say "Use separate terminals so process ownership and cleanup remain explicit."
step "Terminal 1, from this repository: docker compose run --rm --publish 127.0.0.1:8080:8080 emotion-sidecar"
step "Keep the sidecar running. Its first model download and startup may take several minutes."
pause "When the sidecar reports that it is running, press Enter to verify readiness."
if ! curl -fsS http://127.0.0.1:8080/health/ready >/dev/null; then
  fail "The emotion sidecar is not ready. Keep Terminal 1 running, wait for startup, and rerun this wizard."
fi
say "The persistent emotion sidecar is ready. No journal content was sent during this check."
step "Terminal 2, from this repository: mix phx.server"
step "Wait until Phoenix is listening on http://localhost:4000."
step "Terminal 3: cloudflared tunnel --url http://localhost:4000"
step "Copy the generated https://...trycloudflare.com URL."
warn "Keep all three terminals running and keep this machine awake for the entire demo."
printf '  %sPaste the public HTTPS base URL:%s ' "$BOLD" "$RESET"
read -r PUBLIC_BASE_URL || true
PUBLIC_BASE_URL=${PUBLIC_BASE_URL%/}
[[ "$PUBLIC_BASE_URL" =~ ^https://[^/]+$ ]] || fail "Enter only the public HTTPS base URL, without a path."
if ! curl -fsS -o /dev/null "$PUBLIC_BASE_URL/health"; then
  fail "The public health endpoint is unreachable. Check Phoenix and cloudflared, then retry."
fi
say "The public tunnel reaches Alethea's health endpoint."

# ── Stage 6: Telegram webhook registration ─────────────────────────────────
stage "Register the Telegram webhook"
WEBHOOK_URL="$PUBLIC_BASE_URL/webhooks/telegram"
say "Registering the webhook with the same temporary token and secret used for BotConfig."
note "curl receives secrets through stdin configuration, not command arguments or shell history."

if ! TELEGRAM_RESPONSE=$(
  {
    printf 'silent\n'
    printf 'show-error\n'
    printf 'request = "POST"\n'
    printf 'url = "https://api.telegram.org/bot%s/setWebhook"\n' "$TELEGRAM_BOT_TOKEN"
    printf 'form = "url=%s"\n' "$WEBHOOK_URL"
    printf 'form = "secret_token=%s"\n' "$TELEGRAM_WEBHOOK_SECRET"
  } | curl --config -
); then
  fail "Telegram webhook registration request failed. The token was not printed."
fi

if [[ ! "$TELEGRAM_RESPONSE" =~ \"ok\"[[:space:]]*:[[:space:]]*true ]]; then
  fail "Telegram rejected the webhook registration. Check the bot token, secret, and public URL."
fi
unset TELEGRAM_RESPONSE TELEGRAM_BOT_TOKEN TELEGRAM_WEBHOOK_SECRET
say "Telegram accepted the webhook. Temporary bot credentials were cleared from the wizard process."

# ── Stage 7: onboarding and redacted verification ──────────────────────────
stage "Onboard and verify one synthetic message"
warn "REAL PATIENT DATA IS PROHIBITED. Use only the fixed synthetic demo identity."
open_url "$ALETHEA_TELEGRAM_ONBOARDING_URL"
unset ALETHEA_TELEGRAM_ONBOARDING_URL
step "In Telegram, open the bot and send the prefilled /start command."
step "Wait for the synthetic onboarding confirmation."
step "Send one safe synthetic journal entry, for example: 'Today I took a short walk and felt calmer afterward.'"
step "Wait for the AI-generated Telegram reply. Do not send crisis content or identifying details."
pause "After the reply arrives, press Enter for redacted verification commands."

say "Run these from the repository in a third terminal. They never select message bodies, chat IDs, tokens, or AI response text:"
note "Oban inbound/outbound and emotion jobs:"
say "psql \"\${DATABASE_URL:-postgresql://postgres:postgres@localhost/alethea_dev}\" -c \"SELECT id, queue, worker, state, attempt, max_attempts, inserted_at, completed_at FROM oban_jobs WHERE worker IN ('Alethea.Jobs.TelegramOnboardingWorker', 'Alethea.Jobs.TelegramMessageWorker', 'Alethea.Jobs.TelegramOutboundWorker', 'AletheaJobs.EmotionAnalysisWorker') ORDER BY id DESC LIMIT 20;\""
note "Latest Telegram message metadata and AI diagnosis anchor (content remains encrypted/unselected):"
say "psql \"\${DATABASE_URL:-postgresql://postgres:postgres@localhost/alethea_dev}\" -c \"SELECT id, direction, behavior_type, (telegram_message_id IS NOT NULL) AS telegram_inbound, inserted_at FROM messages ORDER BY inserted_at DESC LIMIT 5; SELECT message_id, model_version, inserted_at FROM ai_diagnoses WHERE message_id = (SELECT id FROM messages WHERE telegram_message_id IS NOT NULL ORDER BY inserted_at DESC LIMIT 1) ORDER BY inserted_at DESC;\""
note "Emotion metrics for the latest Telegram inbound message:"
say "psql \"\${DATABASE_URL:-postgresql://postgres:postgres@localhost/alethea_dev}\" -c \"SELECT message_id, model_version, dominant_label, confidence, joy_score, sadness_score, anger_score, fear_score, neutral_score, processed_at FROM emotion_analyses WHERE message_id = (SELECT id FROM messages WHERE telegram_message_id IS NOT NULL ORDER BY inserted_at DESC LIMIT 1);\""
warn "If the quick-tunnel URL changes, rerun this wizard to register the new webhook and mint a fresh onboarding link."

finish
